package com.kubemini.common.error;

public enum ErrorCode {
  DEPLOYMENT_NOT_FOUND,
  NODE_NOT_FOUND,
  POD_NOT_FOUND,
  SERVICE_NOT_FOUND,
  INSUFFICIENT_CLUSTER_RESOURCES,
  SCHEDULING_FAILED,
  VALIDATION_FAILED,
  CONTAINER_RUNTIME_ERROR,
  UNAUTHORIZED,
  CONFLICT
}
